#Schema documentation

Generated by MySQL Workbench Model Documentation v1.0.0 - Copyright (c) 2015 Hieu Le

##Table: `Customers`

###Description: 



###Columns: 

| Column | Data type | Attributes | Default | Description |
| --- | --- | --- | --- | ---  |
| `Customer_id` | INT | PRIMARY, Auto increments, Not null |   |   |
| `FirstName` | VARCHAR(20) | Not null |   |   |
| `LastName` | VARCHAR(20) |  | `NULL` |   |
| `Gender` | VARCHAR(6) |  | `NULL` |   |
| `Address` | VARCHAR(50) |  | `NULL` |   |
| `Phone` | VARCHAR(15) |  | `NULL` |   |
| `Email` | VARCHAR(100) |  | `NULL` |   |
| `City` | VARCHAR(100) |  | `NULL` |   |
| `Country` | VARCHAR(100) |  | `NULL` |   |


### Indices: 

| Name | Columns | Type | Description |
| --- | --- | --- | --- |
| PRIMARY | `Customer_id` | PRIMARY |   |


##Table: `Employees`

###Description: 



###Columns: 

| Column | Data type | Attributes | Default | Description |
| --- | --- | --- | --- | ---  |
| `EmployeeID` | INT | PRIMARY, Auto increments, Not null |   |   |
| `FirstName` | VARCHAR(50) |  | `NULL` |   |
| `Last Name` | VARCHAR(50) |  | `NULL` |   |
| `Email` | VARCHAR(100) |  | `NULL` |   |
| `Job Title` | VARCHAR(50) |  | `NULL` |   |


### Indices: 

| Name | Columns | Type | Description |
| --- | --- | --- | --- |
| PRIMARY | `EmployeeID` | PRIMARY |   |


##Table: `Orders`

###Description: 



###Columns: 

| Column | Data type | Attributes | Default | Description |
| --- | --- | --- | --- | ---  |
| `OrderID` | INT | PRIMARY, Auto increments, Not null |   |   |
| `OrderDate` | DATETIME |  | `NULL` |   |
| `RequiredDate` | DATE |  | `NULL` |   |
| `ShippedDate` | DATE |  | `NULL` |   |
| `Status` | ENUM |  | `'NOTSHIPPED'` |   |


### Indices: 

| Name | Columns | Type | Description |
| --- | --- | --- | --- |
| PRIMARY | `OrderID` | PRIMARY |   |


##Table: `Payments`

###Description: 



###Columns: 

| Column | Data type | Attributes | Default | Description |
| --- | --- | --- | --- | ---  |
| `Customer_id` | INT | PRIMARY, Auto increments, Not null |   |  **foreign key** to column `Customer_id` on table `Customers`. |
| `PaymentDate` | DATETIME |  | `NULL` |   |
| `Amount` | DECIMAL |  | `NULL` |   |


### Indices: 

| Name | Columns | Type | Description |
| --- | --- | --- | --- |
| PRIMARY | `Customer_id` | PRIMARY |   |


##Table: `Products`

###Description: 



###Columns: 

| Column | Data type | Attributes | Default | Description |
| --- | --- | --- | --- | ---  |
| `ProductID` | INT | PRIMARY, Auto increments, Not null |   |   |
| `ProductName` | VARCHAR(50) |  | `NULL` |   |
| `Description` | VARCHAR(255) |  | `NULL` |   |
| `BuyPrice` | DECIMAL | Not null |   |   |


### Indices: 

| Name | Columns | Type | Description |
| --- | --- | --- | --- |
| PRIMARY | `ProductID` | PRIMARY |   |


